language: ruby

services:
  - docker

before_install:
  - docker -v
  - docker-compose -v

install:
  - docker-compose build

before_script:
  - docker-compose run --rm --no-deps web echo 'Gems now pre-installed.'
  - # Use 'run ...` instead of 'exec ...` so that entrypoint's customized bundle install runs completely.
  - docker-compose -f docker-compose.yml up -d
  - # The detached `up` also runs entrypoint — but because it's detached,
  - # bundle install doesn't finish before shell moves on to next commands.
  - docker ps

script:
  - docker-compose run web rails db:migrate RAILS_ENV=test
  - docker-compose run web rails spec

after_script:
  - docker-compose down